#  http.host: "0.0.0.0"
#  xpack.monitoring.elasticsearch.hosts: [ "${ELASTICSEARCH_URL}" ]
#
# ## X-Pack security credentials
# #
xpack.monitoring.enabled: false
# xpack.monitoring.elasticsearch.username: admin
# xpack.monitoring.elasticsearch.password: admin
# xpack.security.transport.ssl.enabled: false
# xpack.security.http.ssl.enabled: false
